### ISSUE TITLE
Chemical Inventory Get All

### ISSUE THREAD

**Issue by timothyhollabaugh** [A-Team-Rowan-University/WebdevFrontend#9]

**Comment by penatem1** [comment]
Back end implemented, structure is ordered and defined as follows:
Name | Type :
- id | unsigned 64 bit integer
- purchaser_id | unsigned 64 bit integer
- custodian_id | unsigned 64 bit integer
- chemical_id | unsigned 64 bit integer

purchaser_id and custodian_id link back to user IDs from the users database.
chemical_id links back to the chemical ID from the chemical database.

If a joined table query is needed for search, it would be easy to do, just let me know. (ie, maybe it's preferred to have the name returned instead of the IDs when searched from the front end. This may be low priority for the Wednesday Demo though)

**Comment by thurstonian** [comment]
Pushed. Needs testing.

**Comment by penatem1** [comment]
Added more fields:
Name | Type :

- storage_location | String
- amount | String
